export const EDOMEX_MUNICIPALITIES = [
  'Acambay de Ruiz Castaneda',
  'Acolman',
  'Aculco',
  'Almoloya de Alquisiras',
  'Almoloya de Juarez',
  'Almoloya del Rio',
  'Amanalco',
  'Amatepec',
  'Amecameca',
  'Apaxco',
  'Atenco',
  'Atizapan',
  'Atizapan de Zaragoza',
  'Atlacomulco',
  'Atlautla',
  'Axapusco',
  'Ayapango',
  'Calimaya',
  'Capulhuac',
  'Coacalco de Berriozabal',
  'Coatepec Harinas',
  'Cocotitlan',
  'Coyotepec',
  'Cuautitlan',
  'Chalco',
  'Chapa de Mota',
  'Chapultepec',
  'Chiautla',
  'Chicoloapan',
  'Chiconcuac',
  'Chimalhuacan',
  'Donato Guerra',
  'Ecatepec de Morelos',
  'Ecatzingo',
  'Huehuetoca',
  'Hueypoxtla',
  'Huixquilucan',
  'Isidro Fabela',
  'Ixtapaluca',
  'Ixtapan de la Sal',
  'Ixtapan del Oro',
  'Ixtlahuaca',
  'Jaltenco',
  'Jilotepec',
  'Jilotzingo',
  'Jiquipilco',
  'Jocotitlan',
  'Joquicingo',
  'Juchitepec',
  'Lerma',
  'Malinalco',
  'Melchor Ocampo',
  'Metepec',
  'Mexicaltzingo',
  'Morelos',
  'Naucalpan de Juarez',
  'Nezahualcoyotl',
  'Nextlalpan',
  'Nicolas Romero',
  'Nopaltepec',
  'Ocoyoacac',
  'Ocuilan',
  'El Oro',
  'Otumba',
  'Otzoloapan',
  'Otzolotepec',
  'Ozumba',
  'Papalotla',
  'La Paz',
  'Polotitlan',
  'Rayon',
  'San Antonio la Isla',
  'San Felipe del Progreso',
  'San Martin de las Piramides',
  'San Mateo Atenco',
  'San Simon de Guerrero',
  'Santo Tomas',
  'Soyaniquilpan de Juarez',
  'Sultepec',
  'Tecamac',
  'Tejupilco',
  'Temamatla',
  'Temascalapa',
  'Temascalcingo',
  'Temascaltepec',
  'Temoaya',
  'Tenancingo',
  'Tenango del Aire',
  'Tenango del Valle',
  'Teoloyucan',
  'Teotihuacan',
  'Tepetlaoxtoc',
  'Tepetlixpa',
  'Tepotzotlan',
  'Tequixquiac',
  'Texcaltitlan',
  'Texcalyacac',
  'Texcoco',
  'Tezoyuca',
  'Tianguistenco',
  'Timilpan',
  'Tlalmanalco',
  'Tlalnepantla de Baz',
  'Tlatlaya',
  'Toluca',
  'Tonatico',
  'Tonanitla',
  'Tultepec',
  'Tultitlan',
  'Valle de Bravo',
  'Valle de Chalco Solidaridad',
  'Villa de Allende',
  'Villa del Carbon',
  'Villa Guerrero',
  'Villa Victoria',
  'Xonacatlan',
  'Zacazonapan',
  'Zacualpan',
  'Zinacantepec',
  'Zumpahuacan',
  'Zumpango',
  'Cuautitlan Izcalli',
  'Luvianos',
  'San Jose del Rincon',
  'Sultepec',
  'Tepetlixpa',
  'Xalatlaco'
] as const;

export const CDMX_ALCALDIAS = [
  'Alvaro Obregon',
  'Azcapotzalco',
  'Benito Juarez',
  'Coyoacan',
  'Cuajimalpa de Morelos',
  'Cuauhtemoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tlahuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco'
] as const;

export const ROUTE_LOCATION_OPTIONS: readonly string[] = Array.from(new Set([...EDOMEX_MUNICIPALITIES, ...CDMX_ALCALDIAS]));

export const ROUTE_SERVICE_SCOPE_OPTIONS = [
  'edomex_to_cdmx',
  'cdmx_to_edomex',
  'mixto_cdmx_edomex'
] as const;

export type RouteServiceScope = (typeof ROUTE_SERVICE_SCOPE_OPTIONS)[number];

export const ROUTE_SERVICE_SCOPE_LABEL: Record<RouteServiceScope, string> = {
  edomex_to_cdmx: 'EdoMex -> CDMX',
  cdmx_to_edomex: 'CDMX -> EdoMex',
  mixto_cdmx_edomex: 'Mixto CDMX / EdoMex'
};

